config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  namespace :admin do
    resources :restaurants
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    self.role == "admin"
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant was successfully created!"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "Restaurant was failed to create."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant)
      flash[:notice] = "restaurant was successfully updated"
    else
      render :edit
      flash[:alert] = "restaurant was failed to update"
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "Restaurant was deleted"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours, :description, :image)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!
  def index

  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here!</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.label :image, "Photo" %>
  <%= image_tag @restaurant.image, width: "300px" if @restaurant.image? %>
  <%= f.file_field :image %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<h1>餐廳後台</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <%= restaurant.name %>
    <%= link_to 'Show', admin_restaurant_path(restaurant) %>
    <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
    <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete,
                          data: { Confirm: "Are you sure?" } %>
  </li>
  <% end %>
</ul>
<%= paginate @restaurants %>
<%= link_to 'New Restaurant', new_admin_restaurant_path %>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here!</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
Opening_hours: <%= @restaurant.opening_hours %><br>
Tel: <%= @restaurant.tel %><br>
Address: <%= @restaurant.address %><br>
Description: <%= @restaurant.description %><br>
<%= image_tag @restaurant.image, width: "600px" %>

<br>

<%= link_to 'Back to index', admin_restaurants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

     <% if current_user %>
      Hi, <%= current_user.email %>
        <%= link_to('登出', destroy_user_session_path, method: :delete) %> |
        <%= link_to('修改密碼', edit_user_registration_path) %>
      <% else %>
        <%= link_to('註冊', new_user_registration_path) %> |
        <%= link_to('登入', new_user_session_path) %>
     <% end %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>餐廳前台</h1>